sudo: required
dist: trusty
language: node_js
node_js:
- 6
branches:
  only:
  - master
install:
- yarn global add grunt-cli
- cd tasks/travis-notify-geckoboard/ && yarn global add stream-browserify && yarn && cd ..
- yarn
script:
- yarn test
after_script:
- node tasks/travis-notify-geckoboard/bin/travis-notify-geckoboard.js -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
cache:
  directories:
  - node_modules
  - tasks/travis-notify-geckoboard/node_modules
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/78a9fadbca7e126c06bc
    on_success: change
    on_failure: always
    on_start: never
